import type { Bilingual } from "@/i18n/config";

/** Every command the terminal knows, in the order `help` lists them. */
export const COMMANDS = [
  "help",
  "about",
  "projects",
  "open",
  "experiments",
  "skills",
  "stack",
  "contact",
  "goto",
  "theme",
  "lang",
  "sound",
  "clear",
  "whoami",
  "ls",
  "cat",
  "date",
  "echo",
  "history",
  "matrix",
  "secret",
  "konami",
  "sudo",
] as const;

export type CommandName = (typeof COMMANDS)[number];

export interface CommandHelp {
  usage: string;
  text: string;
}

/** Help per command. Usage stays the same in both languages (it is code). */
export const commandHelp: Record<CommandName, Bilingual<CommandHelp>> = {
  help: { nl: { usage: "help [commando]", text: "Alle commando's, of uitleg bij een commando." }, en: { usage: "help [command]", text: "All commands, or help for one command." } },
  about: { nl: { usage: "about", text: "Wie Pim is, in feiten." }, en: { usage: "about", text: "Who Pim is, in facts." } },
  projects: { nl: { usage: "projects", text: "De acht projecten, genummerd." }, en: { usage: "projects", text: "The eight projects, numbered." } },
  open: { nl: { usage: "open <slug|nummer>", text: "Opent een project." }, en: { usage: "open <slug|number>", text: "Opens a project." } },
  experiments: { nl: { usage: "experiments", text: "De proeven in het lab." }, en: { usage: "experiments", text: "The experiments in the lab." } },
  skills: { nl: { usage: "skills", text: "Technieken uit Pims projecten, geteld." }, en: { usage: "skills", text: "Technologies from Pim's projects, counted." } },
  stack: { nl: { usage: "stack", text: "Waar deze site mee gebouwd is." }, en: { usage: "stack", text: "What this site is built with." } },
  contact: { nl: { usage: "contact", text: "Waar je Pim vindt." }, en: { usage: "contact", text: "Where to find Pim." } },
  goto: { nl: { usage: "goto <plaat|nummer>", text: "Springt naar een plaat, bijvoorbeeld goto werk of goto 02." }, en: { usage: "goto <plate|number>", text: "Jumps to a plate, for example goto work or goto 02." } },
  theme: { nl: { usage: "theme [dark|light|toggle]", text: "Grafietpapier of katoenpapier." }, en: { usage: "theme [dark|light|toggle]", text: "Graphite paper or cotton paper." } },
  lang: { nl: { usage: "lang [nl|en]", text: "Wisselt van taal." }, en: { usage: "lang [nl|en]", text: "Switches language." } },
  sound: { nl: { usage: "sound [on|off]", text: "Geluid aan of uit." }, en: { usage: "sound [on|off]", text: "Sound on or off." } },
  clear: { nl: { usage: "clear", text: "Maakt het scherm leeg (ook Ctrl+L)." }, en: { usage: "clear", text: "Clears the screen (also Ctrl+L)." } },
  whoami: { nl: { usage: "whoami", text: "Wie jij bent, volgens deze terminal." }, en: { usage: "whoami", text: "Who you are, according to this terminal." } },
  ls: { nl: { usage: "ls", text: "Toont de bestanden." }, en: { usage: "ls", text: "Lists the files." } },
  cat: { nl: { usage: "cat <bestand>", text: "Leest een bestand: about.txt, projects.md of colofon.md." }, en: { usage: "cat <file>", text: "Reads a file: about.txt, projects.md or colofon.md." } },
  date: { nl: { usage: "date", text: "De datum en tijd hier." }, en: { usage: "date", text: "The date and time here." } },
  echo: { nl: { usage: "echo <tekst>", text: "Zegt je tekst terug." }, en: { usage: "echo <text>", text: "Says your text back." } },
  history: { nl: { usage: "history", text: "Wat je eerder typte." }, en: { usage: "history", text: "What you typed before." } },
  matrix: { nl: { usage: "matrix", text: "Letterregen, inkt op papier." }, en: { usage: "matrix", text: "Letter rain, ink on paper." } },
  secret: { nl: { usage: "secret", text: "Er is een verborgen plaat." }, en: { usage: "secret", text: "There is a hidden plate." } },
  konami: { nl: { usage: "konami", text: "Een hint, niet de code." }, en: { usage: "konami", text: "A hint, not the code." } },
  sudo: { nl: { usage: "sudo <iets>", text: "Probeer maar." }, en: { usage: "sudo <anything>", text: "Go on, try." } },
};

export const termCopy = {
  nl: {
    prompt: "pim@vorm ~ %",
    welcome: "Welkom in de terminal van Pim. Typ help, of kies hieronder.",
    tooLong: "Te lang: maximaal 200 tekens.",
    unknown: (input: string) => `Onbekend commando: ${input}.`,
    didYouMean: (cmd: string) => `Bedoelde je ${cmd}? Typ help voor alle commando's.`,
    tryHelp: "Typ help voor alle commando's.",
    helpTitle: "Commando's (een / ervoor mag ook):",
    helpFooter: "Tab vult aan, pijltjes bladeren door je geschiedenis, Esc sluit.",
    noHelpFor: (cmd: string) => `Geen uitleg voor ${cmd}.`,
    aboutIntro: "Pim bouwt software met code en AI. Feiten, met bron:",
    open: "nog in te vullen",
    interests: "Waar zijn projecten vandaan komen:",
    projectsHint: "Typ open 1 tot en met 8, of open <slug>.",
    openUsage: "Gebruik: open <slug|nummer>, bijvoorbeeld open 1 of open teamsync.",
    openUnknown: (arg: string) => `Geen project gevonden voor ${arg}.`,
    opening: (name: string) => `Opent ${name}.`,
    experimentsHint: "Typ goto lab om ze te proberen.",
    skillsIntro: (n: number, p: number) => `${n} technieken uit ${p} projecten, gesorteerd op hoe vaak Pim ze gebruikte:`,
    skillsCol: ["techniek", "projecten"] as [string, string],
    stackIntro: "Deze site is gebouwd met:",
    stackNote: "Gebouwd door Pim met Claude Code.",
    contactIntro: "Pim is te vinden op GitHub:",
    contactPlate: "Of typ goto contact.",
    gotoUsage: "Gebruik: goto <plaat|nummer>. Platen:",
    gotoUnknown: (arg: string) => `Geen plaat gevonden voor ${arg}.`,
    going: (label: string) => `Naar plaat ${label}.`,
    themeNow: (t: string) => `Huidig papier: ${t === "dark" ? "grafiet (dark)" : "katoen (light)"}. Gebruik: theme dark, theme light of theme toggle.`,
    themeSet: (t: string) => (t === "dark" ? "Grafietpapier." : "Katoenpapier."),
    themeBad: "Kies dark, light of toggle.",
    langNow: "Taal: Nederlands. Gebruik: lang en voor Engels.",
    langSet: (l: string) => (l === "en" ? "Switching to English." : "Al Nederlands."),
    langBad: "Kies nl of en.",
    soundNow: (on: boolean) => `Geluid staat ${on ? "aan" : "uit"}. Gebruik: sound on of sound off.`,
    soundSet: (on: boolean) => `Geluid ${on ? "aan" : "uit"}.`,
    soundBad: "Kies on of off.",
    whoami: ["bezoeker", "Je kijkt rond op pim@vorm. De maker heet Pim; jij bent te gast."],
    lsHidden: "Er is ook een verborgen bestand. Probeer ls -a.",
    catUsage: "Gebruik: cat <bestand>. Bestanden: about.txt, projects.md, colofon.md.",
    catUnknown: (f: string) => `cat: ${f}: bestand bestaat niet.`,
    catSecret: "Dit bestand leest niet, het opent. Typ secret.",
    historyEmpty: "Nog geen geschiedenis.",
    echoEmpty: "(niets)",
    matrix: "Letterregen. Esc of een klik stopt het.",
    secret: "Er is een plaat die niet in het rijtje staat. Je wordt erheen gebracht.",
    konami: "Ergens op deze site luistert iets naar een cheatcode uit 1986. Pijltjes, dan twee letters. Niet in een tekstveld.",
    sudo: "Toegang geweigerd. Netjes geprobeerd.",
    cleared: "",
  },
  en: {
    prompt: "pim@vorm ~ %",
    welcome: "Welcome to Pim's terminal. Type help, or pick below.",
    tooLong: "Too long: 200 characters at most.",
    unknown: (input: string) => `Unknown command: ${input}.`,
    didYouMean: (cmd: string) => `Did you mean ${cmd}? Type help for every command.`,
    tryHelp: "Type help for every command.",
    helpTitle: "Commands (a leading / works too):",
    helpFooter: "Tab completes, arrows browse your history, Esc closes.",
    noHelpFor: (cmd: string) => `No help for ${cmd}.`,
    aboutIntro: "Pim builds software with code and AI. Facts, with a source:",
    open: "to be filled in",
    interests: "Where his projects come from:",
    projectsHint: "Type open 1 to 8, or open <slug>.",
    openUsage: "Usage: open <slug|number>, for example open 1 or open teamsync.",
    openUnknown: (arg: string) => `No project found for ${arg}.`,
    opening: (name: string) => `Opening ${name}.`,
    experimentsHint: "Type goto lab to try them.",
    skillsIntro: (n: number, p: number) => `${n} technologies from ${p} projects, sorted by how often Pim used them:`,
    skillsCol: ["technology", "projects"] as [string, string],
    stackIntro: "This site is built with:",
    stackNote: "Built by Pim with Claude Code.",
    contactIntro: "Pim is on GitHub:",
    contactPlate: "Or type goto contact.",
    gotoUsage: "Usage: goto <plate|number>. Plates:",
    gotoUnknown: (arg: string) => `No plate found for ${arg}.`,
    going: (label: string) => `To plate ${label}.`,
    themeNow: (t: string) => `Current paper: ${t === "dark" ? "graphite (dark)" : "cotton (light)"}. Usage: theme dark, theme light or theme toggle.`,
    themeSet: (t: string) => (t === "dark" ? "Graphite paper." : "Cotton paper."),
    themeBad: "Pick dark, light or toggle.",
    langNow: "Language: English. Usage: lang nl for Dutch.",
    langSet: (l: string) => (l === "nl" ? "Naar het Nederlands." : "Already English."),
    langBad: "Pick nl or en.",
    soundNow: (on: boolean) => `Sound is ${on ? "on" : "off"}. Usage: sound on or sound off.`,
    soundSet: (on: boolean) => `Sound ${on ? "on" : "off"}.`,
    soundBad: "Pick on or off.",
    whoami: ["visitor", "You are looking around pim@vorm. The maker is Pim; you are a guest."],
    lsHidden: "There is a hidden file too. Try ls -a.",
    catUsage: "Usage: cat <file>. Files: about.txt, projects.md, colofon.md.",
    catUnknown: (f: string) => `cat: ${f}: no such file.`,
    catSecret: "This file does not read, it opens. Type secret.",
    historyEmpty: "No history yet.",
    echoEmpty: "(nothing)",
    matrix: "Letter rain. Esc or a click stops it.",
    secret: "There is a plate that is not in the row. Taking you there.",
    konami: "Somewhere on this site something listens for a cheat code from 1986. Arrows, then two letters. Not inside a text field.",
    sudo: "Access denied. Nice try.",
    cleared: "",
  },
};

/** Copy for the dialog around the terminal (palette and chrome). */
export const hostCopy = {
  nl: {
    title: "Terminal",
    description: "Zoek een commando, plaat of project, of typ commando's in de terminal.",
    modes: { palette: "Zoeken", terminal: "Terminal" },
    search: "Zoek commando's, platen en projecten",
    searchPlaceholder: "Zoek, bijvoorbeeld werk of teamsync",
    input: "Commando",
    groups: { command: "Commando", plate: "Plaat", project: "Project" },
    empty: (q: string) => `Niets gevonden voor ${q}. Enter voert het uit als commando.`,
    close: "Sluiten",
    chips: "Suggesties",
    output: "Uitvoer van de terminal",
    hintPalette: "pijltjes kiezen · Enter opent · Esc sluit",
    hintTerminal: "Tab vult aan · pijltjes: geschiedenis · Ctrl+L wist · Esc sluit",
  },
  en: {
    title: "Terminal",
    description: "Search a command, plate or project, or type commands in the terminal.",
    modes: { palette: "Search", terminal: "Terminal" },
    search: "Search commands, plates and projects",
    searchPlaceholder: "Search, for example work or teamsync",
    input: "Command",
    groups: { command: "Command", plate: "Plate", project: "Project" },
    empty: (q: string) => `Nothing found for ${q}. Enter runs it as a command.`,
    close: "Close",
    chips: "Suggestions",
    output: "Terminal output",
    hintPalette: "arrows pick · Enter opens · Esc closes",
    hintTerminal: "Tab completes · arrows: history · Ctrl+L clears · Esc closes",
  },
};

export const CHIP_COMMANDS = ["help", "projects", "skills", "about", "goto werk", "theme toggle", "experiments"];
