import type { Bilingual } from "@/i18n/config";

/** Every command the terminal knows, in the order `help` lists them. */
export const COMMANDS = [
  "help",
  "projects",
  "open",
  "goto",
  "contact",
  "theme",
  "lang",
  "whoami",
  "ls",
  "cat",
  "clear",
  "history",
  "echo",
  "matrix",
  "secret",
  "sudo",
] as const;

export type CommandName = (typeof COMMANDS)[number];

export interface CommandHelp {
  usage: string;
  text: string;
}

/** Help per command. Usage stays the same in both languages (it is code). */
export const commandHelp: Record<CommandName, Bilingual<CommandHelp>> = {
  help: { nl: { usage: "help [commando]", text: "Alle commando's, of uitleg bij één commando." }, en: { usage: "help [command]", text: "All commands, or help for one command." } },
  projects: { nl: { usage: "projects", text: "Mijn projecten, genummerd." }, en: { usage: "projects", text: "My projects, numbered." } },
  open: { nl: { usage: "open <slug|nummer>", text: "Opent een project." }, en: { usage: "open <slug|number>", text: "Opens a project." } },
  goto: {
    nl: { usage: "goto <werk|over|lab|contact|home>", text: "Gaat naar een pagina, bijvoorbeeld goto werk." },
    en: { usage: "goto <work|about|lab|contact|home>", text: "Goes to a page, for example goto work." },
  },
  contact: { nl: { usage: "contact", text: "Hoe je me bereikt." }, en: { usage: "contact", text: "How to reach me." } },
  theme: { nl: { usage: "theme [dark|light|toggle]", text: "Donker of licht thema." }, en: { usage: "theme [dark|light|toggle]", text: "Dark or light theme." } },
  lang: { nl: { usage: "lang [nl|en]", text: "Wisselt van taal." }, en: { usage: "lang [nl|en]", text: "Switches language." } },
  whoami: { nl: { usage: "whoami", text: "Wie jij bent, en wie ik ben." }, en: { usage: "whoami", text: "Who you are, and who I am." } },
  ls: { nl: { usage: "ls", text: "Toont de bestanden." }, en: { usage: "ls", text: "Lists the files." } },
  cat: {
    nl: { usage: "cat <bestand>", text: "Leest een bestand: over.txt, projecten.md of diensten.md." },
    en: { usage: "cat <file>", text: "Reads a file: over.txt, projecten.md or diensten.md." },
  },
  clear: { nl: { usage: "clear", text: "Maakt het scherm leeg (ook Ctrl+L)." }, en: { usage: "clear", text: "Clears the screen (also Ctrl+L)." } },
  history: { nl: { usage: "history", text: "Wat je eerder typte." }, en: { usage: "history", text: "What you typed before." } },
  echo: { nl: { usage: "echo <tekst>", text: "Zegt je tekst terug." }, en: { usage: "echo <text>", text: "Says your text back." } },
  matrix: { nl: { usage: "matrix", text: "Letterregen, inkt op papier." }, en: { usage: "matrix", text: "Letter rain, ink on paper." } },
  secret: { nl: { usage: "secret", text: "Er is een pagina die niet in het menu staat." }, en: { usage: "secret", text: "There is a page that is not in the menu." } },
  sudo: { nl: { usage: "sudo <iets>", text: "Probeer maar." }, en: { usage: "sudo <anything>", text: "Go on, try." } },
};

export const termCopy = {
  nl: {
    prompt: "pim ~ %",
    welcome: "Typ help voor alle commando's, of kies hieronder.",
    tooLong: "Te lang: maximaal 200 tekens.",
    unknown: (input: string) => `Onbekend commando: ${input}.`,
    didYouMean: (cmd: string) => `Bedoelde je ${cmd}? Typ help voor alle commando's.`,
    tryHelp: "Typ help voor alle commando's.",
    helpTitle: "Commando's (een / ervoor mag ook):",
    helpFooter: "Tab vult aan, pijltjes bladeren door je geschiedenis, Esc sluit.",
    noHelpFor: (cmd: string) => `Geen uitleg voor ${cmd}.`,
    projectsHint: (count: number) => `Typ open 1 tot en met ${count}, of open <slug>.`,
    openUsage: "Gebruik: open <slug|nummer>, bijvoorbeeld open 1 of open teamsync.",
    openUnknown: (arg: string) => `Geen project gevonden voor ${arg}.`,
    opening: (name: string) => `Opent ${name}.`,
    gotoUsage: "Gebruik: goto <pagina>. Pagina's:",
    gotoUnknown: (arg: string) => `Geen pagina gevonden voor ${arg}.`,
    going: (label: string) => `Naar ${label}.`,
    contactIntro: "Stuur me een bericht via het contactformulier:",
    contactGithub: "Of bekijk mijn code op GitHub:",
    themeNow: (t: string) => `Thema: ${t === "dark" ? "donker" : "licht"}. Gebruik: theme dark, theme light of theme toggle.`,
    themeSet: (t: string) => (t === "dark" ? "Donker thema." : "Licht thema."),
    themeBad: "Kies dark, light of toggle.",
    langNow: "Taal: Nederlands. Gebruik: lang en voor Engels.",
    langSet: (l: string) => (l === "en" ? "Switching to English." : "Al Nederlands."),
    langBad: "Kies nl of en.",
    whoami: ["bezoeker", "Jij bent te gast. Ik ben Pim: ik bouw software die werk uit handen neemt. Typ goto contact als je iets wilt laten bouwen."],
    lsHidden: "Er is ook een verborgen bestand. Probeer ls -a.",
    catUsage: "Gebruik: cat <bestand>. Bestanden: over.txt, projecten.md, diensten.md.",
    catUnknown: (f: string) => `cat: ${f}: bestand bestaat niet.`,
    catSecret: "Dit bestand leest niet, het opent. Typ secret.",
    files: { about: "Over mij", projects: "Projecten", services: "Wat ik kan bouwen" },
    historyEmpty: "Nog geen geschiedenis.",
    echoEmpty: "(niets)",
    matrix: "Letterregen. Esc of een klik stopt het.",
    secret: "Er is een pagina die niet in het menu staat. Je wordt erheen gebracht.",
    sudo: "Toegang geweigerd. Netjes geprobeerd.",
  },
  en: {
    prompt: "pim ~ %",
    welcome: "Type help for every command, or pick below.",
    tooLong: "Too long: 200 characters at most.",
    unknown: (input: string) => `Unknown command: ${input}.`,
    didYouMean: (cmd: string) => `Did you mean ${cmd}? Type help for every command.`,
    tryHelp: "Type help for every command.",
    helpTitle: "Commands (a leading / works too):",
    helpFooter: "Tab completes, arrows browse your history, Esc closes.",
    noHelpFor: (cmd: string) => `No help for ${cmd}.`,
    projectsHint: (count: number) => `Type open 1 to ${count}, or open <slug>.`,
    openUsage: "Usage: open <slug|number>, for example open 1 or open teamsync.",
    openUnknown: (arg: string) => `No project found for ${arg}.`,
    opening: (name: string) => `Opening ${name}.`,
    gotoUsage: "Usage: goto <page>. Pages:",
    gotoUnknown: (arg: string) => `No page found for ${arg}.`,
    going: (label: string) => `To ${label}.`,
    contactIntro: "Send me a message through the contact form:",
    contactGithub: "Or look at my code on GitHub:",
    themeNow: (t: string) => `Theme: ${t}. Usage: theme dark, theme light or theme toggle.`,
    themeSet: (t: string) => (t === "dark" ? "Dark theme." : "Light theme."),
    themeBad: "Pick dark, light or toggle.",
    langNow: "Language: English. Usage: lang nl for Dutch.",
    langSet: (l: string) => (l === "nl" ? "Naar het Nederlands." : "Already English."),
    langBad: "Pick nl or en.",
    whoami: ["visitor", "You are a guest. I am Pim: I build software that takes work off your hands. Type goto contact if you want something built."],
    lsHidden: "There is a hidden file too. Try ls -a.",
    catUsage: "Usage: cat <file>. Files: over.txt, projecten.md, diensten.md.",
    catUnknown: (f: string) => `cat: ${f}: no such file.`,
    catSecret: "This file does not read, it opens. Type secret.",
    files: { about: "About me", projects: "Projects", services: "What I can build" },
    historyEmpty: "No history yet.",
    echoEmpty: "(nothing)",
    matrix: "Letter rain. Esc or a click stops it.",
    secret: "There is a page that is not in the menu. Taking you there.",
    sudo: "Access denied. Nice try.",
  },
};

/** Copy for the dialog around the terminal (palette and chrome). */
export const hostCopy = {
  nl: {
    title: "Snel naar",
    description: "Zoek een pagina, project of commando, of typ commando's in de terminal.",
    modes: { palette: "Zoeken", terminal: "Terminal" },
    search: "Zoek pagina's, projecten en commando's",
    searchPlaceholder: "Zoek, bijvoorbeeld werk of teamsync",
    input: "Commando",
    groups: { command: "Commando", page: "Pagina", project: "Project" },
    empty: (q: string) => `Niets gevonden voor ${q}. Enter voert het uit als commando.`,
    close: "Sluiten",
    chips: "Suggesties",
    output: "Uitvoer van de terminal",
    hintPalette: "pijltjes kiezen · Enter opent · Esc sluit",
    hintTerminal: "Tab vult aan · pijltjes: geschiedenis · Ctrl+L wist · Esc sluit",
  },
  en: {
    title: "Jump to",
    description: "Search a page, project or command, or type commands in the terminal.",
    modes: { palette: "Search", terminal: "Terminal" },
    search: "Search pages, projects and commands",
    searchPlaceholder: "Search, for example work or teamsync",
    input: "Command",
    groups: { command: "Command", page: "Page", project: "Project" },
    empty: (q: string) => `Nothing found for ${q}. Enter runs it as a command.`,
    close: "Close",
    chips: "Suggestions",
    output: "Terminal output",
    hintPalette: "arrows pick · Enter opens · Esc closes",
    hintTerminal: "Tab completes · arrows: history · Ctrl+L clears · Esc closes",
  },
};

export const CHIP_COMMANDS = ["help", "projects", "goto werk", "goto contact", "theme toggle", "whoami"];
